OLED.init(128, 64)
basic.forever(function () {
    OLED.clear()
    OLED.writeString("Nivel de luz : ")
    OLED.writeNumNewLine(Environment.ReadLightIntensity(AnalogPin.P1))
    OLED.writeString("Temperatura  : ")
    OLED.writeNumNewLine(Environment.octopus_BME280(Environment.BME280_state.BME280_temperature_C))
    OLED.writeString("Humedad      : ")
    OLED.writeNumNewLine(Environment.octopus_BME280(Environment.BME280_state.BME280_humidity))
    OLED.writeString("Presion      : ")
    OLED.writeNumNewLine(Environment.octopus_BME280(Environment.BME280_state.BME280_humidity))
    basic.pause(5000)
})
