OLED.init(128, 64)
basic.forever(function () {
    OLED.clear()
    OLED.writeString("Nivel de luz: ")
    OLED.writeNum(Environment.ReadLightIntensity(AnalogPin.P1))
    OLED.newLine()
    OLED.writeString("Temperatura: ")
    OLED.writeNum(Environment.octopus_BME280(Environment.BME280_state.BME280_temperature_C))
    OLED.newLine()
    OLED.writeString("Humedad: ")
    OLED.writeNum(Environment.octopus_BME280(Environment.BME280_state.BME280_humidity))
    OLED.newLine()
    OLED.writeString("Presion: ")
    OLED.writeNum(Environment.octopus_BME280(Environment.BME280_state.BME280_pressure))
    basic.pause(6000)
})
